// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview SEO Analysis Tool flow.
 *
 * - seoAnalysisAndSuggestions - A function that analyzes a website's SEO and provides suggestions for improvement.
 * - SEOAnalysisInput - The input type for the seoAnalysisAndSuggestions function.
 * - SEOAnalysisOutput - The return type for the seoAnalysisAndSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SEOAnalysisInputSchema = z.object({
  websiteUrl: z
    .string()
    .url()
    .describe('The URL of the website to analyze for SEO.'),
  keywords: z
    .string()
    .describe(
      'Comma-separated list of target keywords for which the website should rank.'
    ),
});

export type SEOAnalysisInput = z.infer<typeof SEOAnalysisInputSchema>;

const SEOAnalysisOutputSchema = z.object({
  analysisSummary: z
    .string()
    .describe('A summary of the website SEO analysis.'),
  suggestions: z
    .string()
    .describe(
      'Specific, actionable suggestions for improving the website SEO.'
    ),
});

export type SEOAnalysisOutput = z.infer<typeof SEOAnalysisOutputSchema>;

export async function seoAnalysisAndSuggestions(
  input: SEOAnalysisInput
): Promise<SEOAnalysisOutput> {
  return seoAnalysisFlow(input);
}

const seoAnalysisPrompt = ai.definePrompt({
  name: 'seoAnalysisPrompt',
  input: {schema: SEOAnalysisInputSchema},
  output: {schema: SEOAnalysisOutputSchema},
  prompt: `You are an expert SEO analyst. Analyze the SEO of the website at the following URL: {{websiteUrl}}.
The target keywords for this website are: {{keywords}}.

Provide a detailed analysis summary and specific, actionable suggestions for improvement.

Analysis Summary:
{{analysisSummary}}

Suggestions:
{{suggestions}}`,
});

const seoAnalysisFlow = ai.defineFlow(
  {
    name: 'seoAnalysisFlow',
    inputSchema: SEOAnalysisInputSchema,
    outputSchema: SEOAnalysisOutputSchema,
  },
  async input => {
    const {output} = await seoAnalysisPrompt(input);
    return output!;
  }
);
